#!/usr/bin/env bash

echo "<span foreground='#000000' background='#ffffff'> $(date '+%Y-%m-%d') </span>\
<span foreground='#88C0D0' background='#0f1c21aa'> $(date '+%A') </span>\
<span foreground='#000000' background='#ffffff'> $(date '+%H:%M:%S') </span>"
